### ISSUE TITLE
Number of timepoints per sample

### ISSUE THREAD

**Issue by vitruvi** [ustc-bmec/fMRI-Conv-Att#2]
Since the number of timepoints can itself be informative enough to classify samples, how is the number of timepoints per sample handled in the code? Is there a specific number of timepoints taken from the subtask duration, as in Whole_Brain_Conv? (I couldn't find this information in the journal paper. In the sample.ipynb this number is 15, is it also 15 for all subtasks in the original code?)

(each subtask has a specific number of timepoints and the goal is the classify each subtask, hence the timepoints can spuriously distinguish each subtask.)

**Comment by ustc-bmec** [comment]
The input length of the model is 15. If the inputs are longer than 15, a window of length=15 would be randomly applied to the inputs and obtain a clip of length=15 during the training, leading to an augment in temporal dimension. And the first 15 volumes were clipped during the validating/testing. 
The length of the clips are shown in the table 1 of Jiang 2021's article, the article related to the codes.
